# Generated by Django 3.0 on 2021-10-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb4kApp_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb4kkids',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='bb4kparents',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bb4kkids',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bb4kparents',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
