# Generated by Django 3.0 on 2021-10-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb4kApp_backend', '0002_auto_20211016_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Bb4kKids',
        ),
        migrations.DeleteModel(
            name='Bb4kParents',
        ),
    ]
